[package]
name = "camera-intrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
aprilgrid = "0.3.3"
glam = "0.29.2"
glob = "0.3.1"
image = "0.25.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.10.0"
rerun = "0.17.0"
